name: lbd_phone_input
description: Ultra-flexible phone input field ported from the lbd-phone-input web library.
version: 0.1.0
homepage: https://github.com/lbdsh/lbd-flutter-phone-input
repository: https://github.com/lbdsh/lbd-flutter-phone-input
issue_tracker: https://github.com/lbdsh/lbd-flutter-phone-input/issues
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
